# Generated by Django 4.0.3 on 2022-08-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappoinment',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceappoinment',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
