# Generated by Django 4.0.3 on 2022-08-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_serviceappoinment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceappoinment',
            old_name='assigned_tech',
            new_name='technician',
        ),
    ]
