# Generated by Django 4.0.3 on 2022-08-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_rename_assigned_tech_serviceappoinment_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappoinment',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
